### ISSUE TITLE
Repo description and usage rules

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/community-design-assets#2] opened 2016-11-18 19:58 UTC
Can we get a description for this (and other repos) posted?
I am actually looking for a place to dump an external data-generator tool, but in whatever case some repo rules might be good to have.

**Comment by downeym** [comment] 2016-11-18 23:18
Hmm. I thought that this was a mirror of the canonical repo on GitLab at https://gitlab.com/librehealth/community-design-assets ... but seems like maybe it is reverse? Perhaps @sunbiz or @robbyoconnor can confirm. Either way I agree it needs a README/metadata. It was intended to just be a place to put non-project (general community) design stuff like logo files, promotional material, etc.

**Comment by robbyoconnor** [comment] 2016-11-19 01:21
We could mirror bi-directionally and it won't matter. Like we're doing for lh-ehr.

**Comment by downeym** [comment] 2016-11-19 01:22
Can you confirm what's currently in place?

**Comment by robbyoconnor** [comment] 2016-11-19 01:30
I can put it in place right now. Currently bored so it's doable.

**Comment by robbyoconnor** [comment] 2016-11-19 01:31
Looks like it's mirroring.

**Comment by robbyoconnor** [comment] 2016-11-19 01:31
I'm going to close this.

**Comment by downeym** [comment] 2016-11-19 01:32
![make it so](https://cloud.githubusercontent.com/assets/841003/20451972/ee10f2c8-adb4-11e6-9ce4-28aca21d26b5.gif)

**Closed by robbyoconnor** 2016-11-19 01:31 UTC

**Comment by robbyoconnor** [comment] 2016-11-19 01:33
https://github.com/LibreHealthIO/community-design-assets
